### ISSUE TITLE
No sound after update Easy Effects to `7.1.3`.

### ISSUE THREAD

**Issue by fernvenue** [JackHack96/EasyEffects-Presets#41]
Hi, thanks for this project, I've been using it for a long time, and it works perfectly fine until today, I updated Easy Effect to `7.1.3`, and now it has no sound, but the sound will come back when I remove presets or exclude the apps. Any help will be appreciated.

**Comment by JackHack96** [comment]
Uhm, the problem is not originated by the presets, which are just a bunch of convenient settings for EasyEffects (no audio source change).

The problem you're seeing is more likely to be with audio routing. I've updated to EasyEffects 7.1.3 too but I'm not experiencing the problem.
I'm using the Flatpak version on Ubuntu 20.04, with pipewire instead of PulseAudio.

Unfortunately I'm not very good at troubleshooting the Linux audio stack. The only thing I would suggest is to try uninstalling EasyEffects and its presets, maybe trying the Flatpak version.

**Comment by fernvenue** [comment]
Hi @JackHack96, thank you for your reply, and I just reinstalled EasyEffects and presets, now it works perfectly great, thank you so much. And sorry for the late response :)
