### ISSUE TITLE
Linux beginner - how to install?

### ISSUE THREAD

**Issue by johnstonesnow** [JackHack96/EasyEffects-Presets#43]
...............

**Comment by JackHack96** [comment]
Hello!

Well indeed this repo has a script that automatically installs the presets for you, after you've installed EasyEffects you can open a terminal and type the command you see in the README.

Anyway, I'm not sure if this is going to solve your situation. When you see "Dolby Atmos" on the machine or other things it usually means "Hey we've preinstalled this proprietary software on Windows that automatically tunes the speakers to their best" and in those situations it seems that audio on Windows sounds better, while from Linux seems like from a tin can.
Unfortunately I'm not able to assist you as I'm not an expert in Linux audio.

Try first with my presets (and also with the other maybe: https://github.com/wwmm/easyeffects/wiki/Community-Presets) and see, otherwise I would ask in the Fedora communities.

**Comment by johnstonesnow** [comment]
Thanks very much. Yes I am certainly not expecting (or hoping for) Windows quality audio, I understand what you mean about proprietary Win drivers for 'Dolby Atmos'. But yes, to get it a bit better would be a massive improvement! So I install Easy Effects then run that command, I can do that! Fingers crossed thanks

**Comment by fernvenue** [comment]
Hey, I wanna share my setup :)

First, set up Flathub, follow the [documentation](https://flathub.org/setup), then install [EasyEffects from Flathub](https://flathub.org/apps/com.github.wwmm.easyeffects), enable **Launch Service at System Startup** in preference settings, and finally just use the command in README to install the presets, enjoy.

By the way, I think Flathub will do something clean way, and we don't need to install something manually.
